In [1]:
alist = [1,2,3,4,5,6,7,8,9]
empty=[]
for num in alist:
    empty.append(num*5)
empty


[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [2]:
import numpy as np

In [3]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
numbers + numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
numbers * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
numbers // 5

array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [7]:
numbers / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [11]:
_2darray = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [12]:
_2darray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.size(_2darray)

12

In [14]:
len (_2darray)

4

In [15]:
_2darray.shape

(4, 3)

In [25]:
_2darray = np.arange(20).reshape (4,5)

In [26]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
len(_2darray)

4

In [28]:
np.size(_2darray,0)

4

In [3]:
import numpy as np

In [4]:
tDarray = np.arange(20)

In [5]:
tDarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
tDarray = np.arange(30).reshape(5,6)

In [7]:
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
a= tDarray[0,0]
b= tDarray[1,2]
c= tDarray[0,1]
d= tDarray[1,0]

print(a)
print(b)
print(c)
print(d)

0
8
1
6


In [13]:
tDarray[0,] #row select


array([0, 1, 2, 3, 4, 5])

In [17]:
tDarray[:,0] #column select

array([ 0,  6, 12, 18, 24])

In [20]:
tDarray[0,].ndim #results in dimension of the matrix

1

In [23]:
tDarray[0:3,1:3] #will return matrix after splicing. arrayname [row start: row end + 1, column start: column end +1]

array([[ 1,  2],
       [ 7,  8],
       [13, 14]])

In [24]:
tDarray[3,1:3]

array([19, 20])

In [37]:
tDarray[3,1]

19

In [39]:
d3 = np.arange (100).reshape(5,5,4) #reshape (depth, rows, columns)

In [40]:
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [41]:
d3.ndim

3

In [47]:
d3[1:3,1:,1:]

array([[[25, 26, 27],
        [29, 30, 31],
        [33, 34, 35],
        [37, 38, 39]],

       [[45, 46, 47],
        [49, 50, 51],
        [53, 54, 55],
        [57, 58, 59]]])

In [4]:
a = np.arange(5)

In [6]:
a


array([0, 1, 2, 3, 4])

In [50]:
a >3

array([False, False, False, False,  True])

In [60]:
tDarray[[1,3],:]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [61]:
d3[1:3,[0,3],:]

array([[[20, 21, 22, 23],
        [32, 33, 34, 35]],

       [[40, 41, 42, 43],
        [52, 53, 54, 55]]])

In [10]:
 (a < 2)|( a > 3)

array([ True,  True, False, False,  True])

In [12]:
print(a<3)
np.sum(a<3)

[ True  True  True False False]


3

In [5]:
example = np.arange (9).reshape (3,3)

In [6]:
example

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
example [:2,1:]

array([[1, 2],
       [4, 5]])

In [14]:
example [2:]

array([[6, 7, 8]])

In [17]:
example [2:,:]

array([[6, 7, 8]])

In [18]:
example.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [21]:
example.transpose(1,0)   # transpose (axis0,axis1,.....axisn)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])