In [1]:
alist = [1,2,3,4,5,6,7,8,9]
empty=[]
for num in alist:
    empty.append(num*5)
empty


[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [9]:
import numpy as np

In [3]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
numbers + numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
numbers * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
numbers // 5

array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [7]:
numbers / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [11]:
_2darray = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [12]:
_2darray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.size(_2darray)

12

In [14]:
len (_2darray)

4

In [15]:
_2darray.shape

(4, 3)

In [25]:
_2darray = np.arange(20).reshape (4,5)

In [26]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
len(_2darray)

4

In [28]:
np.size(_2darray,0)

4

In [1]:
import numpy as np

In [4]:
tDarray = np.arange(20)

In [5]:
tDarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
tDarray = np.arange(30).reshape(5,6)

In [7]:
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
a= tDarray[0,0]
b= tDarray[1,2]
c= tDarray[0,1]
d= tDarray[1,0]

print(a)
print(b)
print(c)
print(d)

0
8
1
6


In [13]:
tDarray[0,] #row select


array([0, 1, 2, 3, 4, 5])

In [17]:
tDarray[:,0] #column select

array([ 0,  6, 12, 18, 24])

In [20]:
tDarray[0,].ndim #results in dimension of the matrix

1

In [23]:
tDarray[0:3,1:3] #will return matrix after splicing. arrayname [row start: row end + 1, column start: column end +1]

array([[ 1,  2],
       [ 7,  8],
       [13, 14]])

In [24]:
tDarray[3,1:3]

array([19, 20])